---
# Consult defaults/main.yml to learn about the role variables.
- name: Linux reboot for package upgrades
  include_tasks: linux_reboot.yml
  when: upgrade_packages_reboot_linux

- name: Windows reboot for updates
  win_reboot:
    shutdown_timeout_sec: 3600
    reboot_timeout_sec: 3600
