---
- name: Linux reboot for package upgrades
  include_tasks: latest_packages_reboot_linux.yml
  when: latest_packages_reboot_linux

- name: Windows reboot for updates
  win_reboot:
    shutdown_timeout_sec: 3600
    reboot_timeout_sec: 3600
